import React, { useState, useMemo } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';

const SummaryDisplay = ({ digest, onBack }) => {
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();
  const location = useLocation();

  if (!digest) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-center">
          <div className="w-24 h-24 mx-auto mb-6 rounded-2xl bg-gradient-to-br from-gray-100 to-gray-200 flex items-center justify-center">
            <svg className="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <h3 className="text-xl font-semibold text-gray-900 mb-2">Select a digest to view</h3>
          <p className="text-gray-500">Choose from your recent summaries to see the details</p>
        </div>
      </div>
    );
  }

  // Smart back button logic
  const handleBack = () => {
    if (onBack) {
      // If parent component has onBack callback, use it
      onBack();
    } else if (location.key !== 'default') {
      // If there's history to go back, use browser history
      navigate(-1);
    } else {
      // Otherwise go back to home page
      navigate('/', { replace: true });
    }
  };

  // Parse text format summary to structured data
  const parsedSummary = useMemo(() => {
    let summaryText = digest.summary;
    
    // If it's a JSON string, try to parse
    if (typeof summaryText === 'string' && summaryText.startsWith('{')) {
      try {
        return JSON.parse(summaryText);
      } catch (e) {
        // If not valid JSON, continue processing as text
      }
    }

    // Parse text format summary
    if (typeof summaryText === 'string') {
      const result = {
        title: 'Meeting Summary',
        overview: '',
        keyDecisions: [],
        actionItems: [],
        nextSteps: []
      };

      // Extract overview (first paragraph)
      const lines = summaryText.split('\n').filter(line => line.trim());
      const firstParagraph = lines.find(line => !line.includes('**') && !line.includes('•') && !line.includes('*') && line.length > 50);
      if (firstParagraph) {
        result.overview = firstParagraph.trim();
      }

      // Extract key decisions
      const decisionsMatch = summaryText.match(/\*\*Key Decisions Made:\*\*(.*?)(?=\*\*|$)/s);
      if (decisionsMatch) {
        const decisions = decisionsMatch[1]
          .split('•')
          .map(item => item.replace(/Decision:\s*/, '').trim())
          .filter(item => item && item.length > 10);
        result.keyDecisions = decisions;
      }

      // Extract action items
      const actionsMatch = summaryText.match(/\*\*Action Items:\*\*(.*?)(?=\*\*|$)/s);
      if (actionsMatch) {
        const actions = actionsMatch[1]
          .split('•')
          .map(item => {
            const cleanItem = item.replace(/Action:\s*/, '').trim();
            const parts = cleanItem.split(' to ');
            if (parts.length >= 2) {
              return {
                task: parts.slice(1).join(' to ').trim(),
                assignee: parts[0].trim(),
                deadline: cleanItem.includes('by ') ? cleanItem.match(/by (\w+)/)?.[1] : 'TBD'
              };
            }
            return { task: cleanItem, assignee: 'TBD', deadline: 'TBD' };
          })
          .filter(item => item.task && item.task.length > 5);
        result.actionItems = actions;
      }

      // Extract next steps
      const stepsMatch = summaryText.match(/\*\*Important Next Steps:\*\*(.*?)$/s);
      if (stepsMatch) {
        const steps = stepsMatch[1]
          .split('*')
          .map(item => item.trim())
          .filter(item => item && item.length > 10);
        result.nextSteps = steps;
      }

      return result;
    }

    return summaryText || {};
  }, [digest.summary]);

  const handleShare = async () => {
    // Check if public_id exists
    if (!digest.public_id) {
      // If no public_id, generate a simple share URL
      const shareContent = `Meeting Summary: ${parsedSummary?.title || 'Meeting Summary'}

Overview: ${parsedSummary?.overview || 'Meeting summary available'}

Generated by Meeting Digest - Transform your meetings into actionable insights!
${window.location.origin}`;

      try {
        if (navigator.share) {
          // Use Web Share API (mobile-friendly)
          await navigator.share({
            title: parsedSummary?.title || 'Meeting Summary',
            text: shareContent,
            url: window.location.origin
          });
        } else {
          // Fallback to copy text
          await navigator.clipboard.writeText(shareContent);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        }
      } catch (err) {
        console.error('Share failed:', err);
        // Last fallback - show text for manual copy
        prompt('Copy this text to share:', shareContent);
      }
    } else {
      // If public_id exists, use original share logic
      const shareUrl = `${window.location.origin}/shared/${digest.public_id}`;
      try {
        if (navigator.share) {
          await navigator.share({
            title: parsedSummary?.title || 'Meeting Summary',
            text: 'Check out this meeting summary',
            url: shareUrl
          });
        } else {
          await navigator.clipboard.writeText(shareUrl);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        }
      } catch (err) {
        console.error('Failed to share:', err);
        prompt('Copy this link to share:', shareUrl);
      }
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <div className="p-8">
      {/* Beautiful header - add back button */}
      <div className="flex items-start justify-between mb-8 pb-6 border-b border-gray-100">
        <div className="flex-1">
          {/* Back button */}
          <button
            onClick={handleBack}
            className="group flex items-center space-x-2 text-gray-600 hover:text-gray-900 transition-colors mb-4"
          >
            <svg className="w-4 h-4 group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            <span className="text-sm font-medium">Back</span>
          </button>

          <div className="flex items-center space-x-3 mb-3">
            <div className="w-3 h-3 bg-green-400 rounded-full animate-pulse"></div>
            <span className="text-sm font-medium text-green-600">AI Generated</span>
          </div>
          
          <h1 className="text-3xl font-bold text-gray-900 mb-3 leading-tight">
            {parsedSummary?.title || 'Meeting Summary'}
          </h1>
          
          <div className="flex items-center space-x-4 text-sm text-gray-500">
            <div className="flex items-center space-x-2">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span>{formatDate(digest.created_at)}</span>
            </div>
            <div className="flex items-center space-x-2">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span>Processed</span>
            </div>
          </div>
        </div>
        
        {/* Improved share button */}
        <button
          onClick={handleShare}
          className="group px-6 py-3 bg-gradient-to-r from-blue-500 to-blue-600 text-white font-medium rounded-xl hover:from-blue-600 hover:to-blue-700 transition-all duration-200 flex items-center space-x-2 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
        >
          <svg className="w-4 h-4 group-hover:scale-110 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" />
          </svg>
          <span>{copied ? 'Copied!' : 'Share'}</span>
        </button>
      </div>

      {/* Overview card */}
      {parsedSummary?.overview && (
        <div className="mb-8">
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-8 border border-blue-100">
            <div className="flex items-center space-x-2 mb-4">
              <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
              </svg>
              <h2 className="font-semibold text-blue-900">Meeting Overview</h2>
            </div>
            <p className="text-lg text-blue-800 leading-relaxed font-light">
              {parsedSummary.overview}
            </p>
          </div>
        </div>
      )}

      {/* Content grid */}
      <div className="grid gap-8">
        {/* Key decisions */}
        {parsedSummary?.keyDecisions && parsedSummary.keyDecisions.length > 0 && (
          <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <div className="bg-gradient-to-r from-purple-50 to-pink-50 px-6 py-4 border-b border-gray-100">
              <div className="flex items-center space-x-2">
                <svg className="w-5 h-5 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
                <h2 className="font-semibold text-purple-900">Key Decisions</h2>
                <span className="px-2 py-1 bg-purple-100 text-purple-600 text-xs font-medium rounded-full">
                  {parsedSummary.keyDecisions.length}
                </span>
              </div>
            </div>
            <div className="p-6 space-y-4">
              {parsedSummary.keyDecisions.map((decision, index) => (
                <div key={index} className="flex items-start space-x-3 group">
                  <div className="w-6 h-6 rounded-full bg-purple-100 flex items-center justify-center flex-shrink-0 mt-1 group-hover:bg-purple-200 transition-colors">
                    <svg className="w-3 h-3 text-purple-600" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <p className="text-gray-700 leading-relaxed flex-1">{decision}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Action items */}
        {parsedSummary?.actionItems && parsedSummary.actionItems.length > 0 && (
          <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <div className="bg-gradient-to-r from-green-50 to-emerald-50 px-6 py-4 border-b border-gray-100">
              <div className="flex items-center space-x-2">
                <svg className="w-5 h-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z" clipRule="evenodd" />
                </svg>
                <h2 className="font-semibold text-green-900">Action Items</h2>
                <span className="px-2 py-1 bg-green-100 text-green-600 text-xs font-medium rounded-full">
                  {parsedSummary.actionItems.length}
                </span>
              </div>
            </div>
            <div className="p-6 space-y-4">
              {parsedSummary.actionItems.map((item, index) => (
                <div key={index} className="bg-gradient-to-r from-green-50/50 to-emerald-50/50 rounded-xl p-4 border border-green-100 hover:border-green-200 transition-colors">
                  <div className="flex items-start space-x-4">
                    <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                      <svg className="w-4 h-4 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <div className="flex-1">
                      <p className="text-gray-900 font-medium mb-2 leading-snug">{item.task}</p>
                      <div className="flex flex-wrap gap-3 text-sm">
                        {item.assignee && item.assignee !== 'TBD' && (
                          <span className="inline-flex items-center px-2 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-medium">
                            <svg className="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 20 20">
                              <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd" />
                            </svg>
                            {item.assignee}
                          </span>
                        )}
                        {item.deadline && item.deadline !== 'TBD' && (
                          <span className="inline-flex items-center px-2 py-1 bg-orange-100 text-orange-700 rounded-full text-xs font-medium">
                            <svg className="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 20 20">
                              <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                            </svg>
                            {item.deadline}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Next steps */}
        {parsedSummary?.nextSteps && parsedSummary.nextSteps.length > 0 && (
          <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <div className="bg-gradient-to-r from-orange-50 to-amber-50 px-6 py-4 border-b border-gray-100">
              <div className="flex items-center space-x-2">
                <svg className="w-5 h-5 text-orange-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
                </svg>
                <h2 className="font-semibold text-orange-900">Next Steps</h2>
                <span className="px-2 py-1 bg-orange-100 text-orange-600 text-xs font-medium rounded-full">
                  {parsedSummary.nextSteps.length}
                </span>
              </div>
            </div>
            <div className="p-6 space-y-4">
              {parsedSummary.nextSteps.map((step, index) => (
                <div key={index} className="flex items-start space-x-3 group">
                  <div className="w-6 h-6 rounded-full bg-orange-100 flex items-center justify-center flex-shrink-0 mt-1 group-hover:bg-orange-200 transition-colors">
                    <span className="text-orange-600 text-xs font-bold">{index + 1}</span>
                  </div>
                  <p className="text-gray-700 leading-relaxed flex-1">{step}</p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* If no structured data, show original content */}
        {(!parsedSummary?.keyDecisions?.length && !parsedSummary?.actionItems?.length && !parsedSummary?.nextSteps?.length) && (
          <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <div className="bg-gradient-to-r from-gray-50 to-slate-50 px-6 py-4 border-b border-gray-100">
              <div className="flex items-center space-x-2">
                <svg className="w-5 h-5 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z" clipRule="evenodd" />
                </svg>
                <h2 className="font-semibold text-gray-900">Summary Content</h2>
              </div>
            </div>
            <div className="p-6">
              <div className="prose prose-gray max-w-none">
                <div className="whitespace-pre-wrap text-gray-700 leading-relaxed">
                  {typeof digest.summary === 'string' ? digest.summary : JSON.stringify(digest.summary, null, 2)}
                </div>
              </div>
            </div>
          </section>
        )}
      </div>

      {/* Statistics */}
      <div className="mt-12 grid grid-cols-3 gap-4">
        <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl p-4 text-center">
          <div className="text-2xl font-bold text-blue-600">
            {(parsedSummary?.keyDecisions?.length || 0) + (parsedSummary?.actionItems?.length || 0) + (parsedSummary?.nextSteps?.length || 0)}
          </div>
          <div className="text-sm text-blue-700 font-medium">Total Items</div>
        </div>
        <div className="bg-gradient-to-br from-green-50 to-green-100 rounded-xl p-4 text-center">
          <div className="text-2xl font-bold text-green-600">
            {parsedSummary?.actionItems?.length || 0}
          </div>
          <div className="text-sm text-green-700 font-medium">Action Items</div>
        </div>
        <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-xl p-4 text-center">
          <div className="text-2xl font-bold text-purple-600">
            {parsedSummary?.keyDecisions?.length || 0}
          </div>
          <div className="text-sm text-purple-700 font-medium">Decisions</div>
        </div>
      </div>
    </div>
  );
};

export default SummaryDisplay;